language: python
python:
  - "3.5"

install:
  - pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:
  # - pylint rxaws
  - coverage run --source=rxaws setup.py nosetests -w tests.unit 

after_success:
  - coveralls
